const SECONDS_PER_MINUTE = 60;

export const MINUTES_PER_HOUR = 60;
export const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
export const SECONDS_PER_DAY = SECONDS_PER_HOUR * 24;
export const MILLISECONDS_PER_SECOND = 1000;

export const OAUTH_EXCHANGE_EXPIRY = 10 * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;